// Code generated by go-swagger; DO NOT EDIT.

// Package restapi vsphere-rest-server
//
//	HTTP server in Go with Swagger endpoints definition
//	Schemes:
//	  https
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
