// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "vsphere-rest-server",
    "version": "0.1.0"
  },
  "paths": {
    "/session/list": {
      "get": {
        "operationId": "SessionList",
        "responses": {
          "200": {
            "description": "Lists the sessions in use on the server",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "Connections": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "url": {
                          "type": "string"
                        },
                        "username": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "Host": {
                    "type": "string"
                  },
                  "LastAccess": {
                    "type": "string"
                  },
                  "Secret": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/session/register": {
      "post": {
        "summary": "Register a new Session",
        "operationId": "SessionRegister",
        "parameters": [
          {
            "description": "something",
            "name": "requestBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "secret"
              ],
              "properties": {
                "secret": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Registers the user session",
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "description": "The token the user should provide for future requests.",
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Session already exists."
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "description": "The error message for failure.",
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/vsphere/connect": {
      "post": {
        "summary": "Connect to a vCenter or ESXi Server",
        "operationId": "vSphereConnect",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "description": "something",
            "name": "requestBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "url",
                "username",
                "password"
              ],
              "properties": {
                "allow_insecure": {
                  "type": "boolean"
                },
                "name": {
                  "description": "A nicename for the connection. If not set, then it is the hostname part of the URL (made unique)",
                  "type": "string"
                },
                "passthrough": {
                  "type": "boolean"
                },
                "password": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "schema": {
              "type": "object",
              "properties": {
                "about": {
                  "type": "object"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "A generic failure message, the reason for which is in the attached error message.",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Invalid Token was passed, this is an unauthenicated request."
          },
          "403": {
            "description": "Permission issue on the target vCenter Server/ESXi."
          },
          "404": {
            "description": "The target server could not be found."
          }
        }
      }
    },
    "/vsphere/list": {
      "get": {
        "summary": "Provides a list of all vSphere Connections",
        "operationId": "vSphereListConnections",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid Token was passed, this is an unauthenicated request."
          }
        }
      }
    },
    "/vsphere/{vcenter}/cluster": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllClusters",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/datacenter": {
      "get": {
        "summary": "Gets the datacenters.",
        "operationId": "vSphereGetAllDatacenters",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/datastore": {
      "get": {
        "summary": "Get a list of datastores",
        "operationId": "vSphereGetAllDatastores",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/host": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllHostsSummary",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/host/name/{hostname}": {
      "get": {
        "summary": "Retrieve full details from a Host by the name of the host.",
        "operationId": "vSphereGetHostByName",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          },
          {
            "$ref": "#/parameters/HostName"
          },
          {
            "$ref": "#/parameters/SOAPProperties"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/host/ref/{moref}": {
      "get": {
        "summary": "Retrieve full details from a Host by it's Managed Object Reference.",
        "operationId": "vSphereGetHostByMoRef",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          },
          {
            "$ref": "#/parameters/ManagedReference"
          },
          {
            "$ref": "#/parameters/SOAPProperties"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/network": {
      "get": {
        "summary": "Gets a list of networks",
        "operationId": "vSphereGetAllNetworks",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/resourcepool": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllResourcePool",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/storagepod": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllStoragePods",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/": {
      "get": {
        "summary": "Retrieve a summary of all Virtual Machines from a vCenter Server/ESXi host.",
        "operationId": "vSphereGetAllVMSummary",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "count": {
                  "type": "integer"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "cpu": {
                        "type": "integer"
                      },
                      "guestFullName": {
                        "type": "string"
                      },
                      "hardwareVersion": {
                        "type": "string"
                      },
                      "memoryMB": {
                        "type": "integer"
                      },
                      "moref": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "numberDisks": {
                        "type": "integer"
                      },
                      "numberNICs": {
                        "type": "integer"
                      },
                      "powerstate": {
                        "type": "string"
                      },
                      "status": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/name/{vmname}": {
      "get": {
        "summary": "Retrieve a VM from a vCenter Server/ESXi host.",
        "operationId": "vSphereGetVMByName",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          },
          {
            "$ref": "#/parameters/VirtualMachineName"
          },
          {
            "$ref": "#/parameters/SOAPProperties"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/ref/{moref}": {
      "get": {
        "summary": "Retrieve a VM from a vCenter Server/ESXi host by it's Managed Object Reference.",
        "operationId": "vSphereGetVMByMoRef",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          },
          {
            "$ref": "#/parameters/ManagedReference"
          },
          {
            "$ref": "#/parameters/SOAPProperties"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ObjectCollectionResponse"
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/{moref}/power": {
      "post": {
        "summary": "Power actions on the VM.",
        "operationId": "vSphereChangeVMPowerState",
        "parameters": [
          {
            "$ref": "#/parameters/VRSToken"
          },
          {
            "$ref": "#/parameters/vCenter"
          },
          {
            "$ref": "#/parameters/ManagedReference"
          },
          {
            "enum": [
              "on",
              "off",
              "standby"
            ],
            "type": "string",
            "description": "The desired power state.",
            "name": "state",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The power state change task has been initiated."
          },
          "400": {
            "$ref": "#/responses/GeneralFailureResponse"
          }
        }
      }
    }
  },
  "definitions": {
    "BadRequestError": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string"
        }
      }
    },
    "ObjectCollection": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "results": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  },
  "parameters": {
    "HostName": {
      "type": "string",
      "description": "The name of the ESXi host",
      "name": "hostname",
      "in": "path",
      "required": true
    },
    "ManagedReference": {
      "type": "string",
      "description": "The Managed Object Reference for the Virtual Machine in the format (type-XXXX)",
      "name": "moref",
      "in": "path",
      "required": true
    },
    "SOAPProperties": {
      "type": "string",
      "description": "A comma-delimited list of the properties to retrieve from the VM.",
      "name": "props",
      "in": "query"
    },
    "VRSToken": {
      "type": "string",
      "name": "VRS-Token",
      "in": "header",
      "required": true
    },
    "VirtualMachineName": {
      "type": "string",
      "description": "The name of the virtual machine",
      "name": "vmname",
      "in": "path",
      "required": true
    },
    "vCenter": {
      "type": "string",
      "description": "The nicename for the connection.",
      "name": "vcenter",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "GeneralFailureResponse": {
      "description": "A general failure occured, more details are contained within the message.",
      "schema": {
        "$ref": "#/definitions/BadRequestError"
      }
    },
    "ObjectCollectionResponse": {
      "description": "Successful request. Returns JSON containing a count and the collection of objects.",
      "schema": {
        "$ref": "#/definitions/ObjectCollection"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "vsphere-rest-server",
    "version": "0.1.0"
  },
  "paths": {
    "/session/list": {
      "get": {
        "operationId": "SessionList",
        "responses": {
          "200": {
            "description": "Lists the sessions in use on the server",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SessionListOKBodyItems0"
              }
            }
          }
        }
      }
    },
    "/session/register": {
      "post": {
        "summary": "Register a new Session",
        "operationId": "SessionRegister",
        "parameters": [
          {
            "description": "something",
            "name": "requestBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "secret"
              ],
              "properties": {
                "secret": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Registers the user session",
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "description": "The token the user should provide for future requests.",
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Session already exists."
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "description": "The error message for failure.",
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/vsphere/connect": {
      "post": {
        "summary": "Connect to a vCenter or ESXi Server",
        "operationId": "vSphereConnect",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "description": "something",
            "name": "requestBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "url",
                "username",
                "password"
              ],
              "properties": {
                "allow_insecure": {
                  "type": "boolean"
                },
                "name": {
                  "description": "A nicename for the connection. If not set, then it is the hostname part of the URL (made unique)",
                  "type": "string"
                },
                "passthrough": {
                  "type": "boolean"
                },
                "password": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "schema": {
              "type": "object",
              "properties": {
                "about": {
                  "type": "object"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "A generic failure message, the reason for which is in the attached error message.",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Invalid Token was passed, this is an unauthenicated request."
          },
          "403": {
            "description": "Permission issue on the target vCenter Server/ESXi."
          },
          "404": {
            "description": "The target server could not be found."
          }
        }
      }
    },
    "/vsphere/list": {
      "get": {
        "summary": "Provides a list of all vSphere Connections",
        "operationId": "vSphereListConnections",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/VSphereListConnectionsOKBodyItems0"
              }
            }
          },
          "401": {
            "description": "Invalid Token was passed, this is an unauthenicated request."
          }
        }
      }
    },
    "/vsphere/{vcenter}/cluster": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllClusters",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/datacenter": {
      "get": {
        "summary": "Gets the datacenters.",
        "operationId": "vSphereGetAllDatacenters",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/datastore": {
      "get": {
        "summary": "Get a list of datastores",
        "operationId": "vSphereGetAllDatastores",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/host": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllHostsSummary",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/host/name/{hostname}": {
      "get": {
        "summary": "Retrieve full details from a Host by the name of the host.",
        "operationId": "vSphereGetHostByName",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the ESXi host",
            "name": "hostname",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "A comma-delimited list of the properties to retrieve from the VM.",
            "name": "props",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/host/ref/{moref}": {
      "get": {
        "summary": "Retrieve full details from a Host by it's Managed Object Reference.",
        "operationId": "vSphereGetHostByMoRef",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The Managed Object Reference for the Virtual Machine in the format (type-XXXX)",
            "name": "moref",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "A comma-delimited list of the properties to retrieve from the VM.",
            "name": "props",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/network": {
      "get": {
        "summary": "Gets a list of networks",
        "operationId": "vSphereGetAllNetworks",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/resourcepool": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllResourcePool",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/storagepod": {
      "get": {
        "summary": "Gets the hosts found at the endpoint.",
        "operationId": "vSphereGetAllStoragePods",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/": {
      "get": {
        "summary": "Retrieve a summary of all Virtual Machines from a vCenter Server/ESXi host.",
        "operationId": "vSphereGetAllVMSummary",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "count": {
                  "type": "integer"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResultsItems0"
                  }
                }
              }
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/name/{vmname}": {
      "get": {
        "summary": "Retrieve a VM from a vCenter Server/ESXi host.",
        "operationId": "vSphereGetVMByName",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the virtual machine",
            "name": "vmname",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "A comma-delimited list of the properties to retrieve from the VM.",
            "name": "props",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/ref/{moref}": {
      "get": {
        "summary": "Retrieve a VM from a vCenter Server/ESXi host by it's Managed Object Reference.",
        "operationId": "vSphereGetVMByMoRef",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The Managed Object Reference for the Virtual Machine in the format (type-XXXX)",
            "name": "moref",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "A comma-delimited list of the properties to retrieve from the VM.",
            "name": "props",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request. Returns JSON containing a count and the collection of objects.",
            "schema": {
              "$ref": "#/definitions/ObjectCollection"
            }
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    },
    "/vsphere/{vcenter}/vm/{moref}/power": {
      "post": {
        "summary": "Power actions on the VM.",
        "operationId": "vSphereChangeVMPowerState",
        "parameters": [
          {
            "type": "string",
            "name": "VRS-Token",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "The nicename for the connection.",
            "name": "vcenter",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The Managed Object Reference for the Virtual Machine in the format (type-XXXX)",
            "name": "moref",
            "in": "path",
            "required": true
          },
          {
            "enum": [
              "on",
              "off",
              "standby"
            ],
            "type": "string",
            "description": "The desired power state.",
            "name": "state",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The power state change task has been initiated."
          },
          "400": {
            "description": "A general failure occured, more details are contained within the message.",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BadRequestError": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string"
        }
      }
    },
    "ObjectCollection": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "results": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    },
    "ResultsItems0": {
      "type": "object",
      "properties": {
        "cpu": {
          "type": "integer"
        },
        "guestFullName": {
          "type": "string"
        },
        "hardwareVersion": {
          "type": "string"
        },
        "memoryMB": {
          "type": "integer"
        },
        "moref": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "numberDisks": {
          "type": "integer"
        },
        "numberNICs": {
          "type": "integer"
        },
        "powerstate": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "SessionListOKBodyItems0": {
      "type": "object",
      "properties": {
        "Connections": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SessionListOKBodyItems0ConnectionsItems0"
          }
        },
        "Host": {
          "type": "string"
        },
        "LastAccess": {
          "type": "string"
        },
        "Secret": {
          "type": "string"
        }
      }
    },
    "SessionListOKBodyItems0ConnectionsItems0": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "VSphereListConnectionsOKBodyItems0": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "HostName": {
      "type": "string",
      "description": "The name of the ESXi host",
      "name": "hostname",
      "in": "path",
      "required": true
    },
    "ManagedReference": {
      "type": "string",
      "description": "The Managed Object Reference for the Virtual Machine in the format (type-XXXX)",
      "name": "moref",
      "in": "path",
      "required": true
    },
    "SOAPProperties": {
      "type": "string",
      "description": "A comma-delimited list of the properties to retrieve from the VM.",
      "name": "props",
      "in": "query"
    },
    "VRSToken": {
      "type": "string",
      "name": "VRS-Token",
      "in": "header",
      "required": true
    },
    "VirtualMachineName": {
      "type": "string",
      "description": "The name of the virtual machine",
      "name": "vmname",
      "in": "path",
      "required": true
    },
    "vCenter": {
      "type": "string",
      "description": "The nicename for the connection.",
      "name": "vcenter",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "GeneralFailureResponse": {
      "description": "A general failure occured, more details are contained within the message.",
      "schema": {
        "$ref": "#/definitions/BadRequestError"
      }
    },
    "ObjectCollectionResponse": {
      "description": "Successful request. Returns JSON containing a count and the collection of objects.",
      "schema": {
        "$ref": "#/definitions/ObjectCollection"
      }
    }
  }
}`))
}
