// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetVMByMoRefOKCode is the HTTP code returned for type VSphereGetVMByMoRefOK
const VSphereGetVMByMoRefOKCode int = 200

/*
VSphereGetVMByMoRefOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetVmByMoRefOK
*/
type VSphereGetVMByMoRefOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetVMByMoRefOK creates VSphereGetVMByMoRefOK with default headers values
func NewVSphereGetVMByMoRefOK() *VSphereGetVMByMoRefOK {

	return &VSphereGetVMByMoRefOK{}
}

// WithPayload adds the payload to the v sphere get Vm by mo ref o k response
func (o *VSphereGetVMByMoRefOK) WithPayload(payload *models.ObjectCollection) *VSphereGetVMByMoRefOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get Vm by mo ref o k response
func (o *VSphereGetVMByMoRefOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetVMByMoRefOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetVMByMoRefBadRequestCode is the HTTP code returned for type VSphereGetVMByMoRefBadRequest
const VSphereGetVMByMoRefBadRequestCode int = 400

/*
VSphereGetVMByMoRefBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetVmByMoRefBadRequest
*/
type VSphereGetVMByMoRefBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetVMByMoRefBadRequest creates VSphereGetVMByMoRefBadRequest with default headers values
func NewVSphereGetVMByMoRefBadRequest() *VSphereGetVMByMoRefBadRequest {

	return &VSphereGetVMByMoRefBadRequest{}
}

// WithPayload adds the payload to the v sphere get Vm by mo ref bad request response
func (o *VSphereGetVMByMoRefBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetVMByMoRefBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get Vm by mo ref bad request response
func (o *VSphereGetVMByMoRefBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetVMByMoRefBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
