// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewVSphereChangeVMPowerStateParams creates a new VSphereChangeVMPowerStateParams object
//
// There are no default values defined in the spec.
func NewVSphereChangeVMPowerStateParams() VSphereChangeVMPowerStateParams {

	return VSphereChangeVMPowerStateParams{}
}

// VSphereChangeVMPowerStateParams contains all the bound params for the v sphere change VM power state operation
// typically these are obtained from a http.Request
//
// swagger:parameters vSphereChangeVMPowerState
type VSphereChangeVMPowerStateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: header
	*/
	VRSToken string
	/*The Managed Object Reference for the Virtual Machine in the format (type-XXXX)
	  Required: true
	  In: path
	*/
	Moref string
	/*The desired power state.
	  Required: true
	  In: query
	*/
	State string
	/*The nicename for the connection.
	  Required: true
	  In: path
	*/
	Vcenter string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewVSphereChangeVMPowerStateParams() beforehand.
func (o *VSphereChangeVMPowerStateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if err := o.bindVRSToken(r.Header[http.CanonicalHeaderKey("VRS-Token")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rMoref, rhkMoref, _ := route.Params.GetOK("moref")
	if err := o.bindMoref(rMoref, rhkMoref, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}

	rVcenter, rhkVcenter, _ := route.Params.GetOK("vcenter")
	if err := o.bindVcenter(rVcenter, rhkVcenter, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindVRSToken binds and validates parameter VRSToken from header.
func (o *VSphereChangeVMPowerStateParams) bindVRSToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("VRS-Token", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("VRS-Token", "header", raw); err != nil {
		return err
	}
	o.VRSToken = raw

	return nil
}

// bindMoref binds and validates parameter Moref from path.
func (o *VSphereChangeVMPowerStateParams) bindMoref(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Moref = raw

	return nil
}

// bindState binds and validates parameter State from query.
func (o *VSphereChangeVMPowerStateParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("state", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("state", "query", raw); err != nil {
		return err
	}
	o.State = raw

	if err := o.validateState(formats); err != nil {
		return err
	}

	return nil
}

// validateState carries on validations for parameter State
func (o *VSphereChangeVMPowerStateParams) validateState(formats strfmt.Registry) error {

	if err := validate.EnumCase("state", "query", o.State, []interface{}{"on", "off", "standby"}, true); err != nil {
		return err
	}

	return nil
}

// bindVcenter binds and validates parameter Vcenter from path.
func (o *VSphereChangeVMPowerStateParams) bindVcenter(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Vcenter = raw

	return nil
}
