// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewVSphereListConnectionsParams creates a new VSphereListConnectionsParams object
//
// There are no default values defined in the spec.
func NewVSphereListConnectionsParams() VSphereListConnectionsParams {

	return VSphereListConnectionsParams{}
}

// VSphereListConnectionsParams contains all the bound params for the v sphere list connections operation
// typically these are obtained from a http.Request
//
// swagger:parameters vSphereListConnections
type VSphereListConnectionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: header
	*/
	VRSToken string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewVSphereListConnectionsParams() beforehand.
func (o *VSphereListConnectionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindVRSToken(r.Header[http.CanonicalHeaderKey("VRS-Token")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindVRSToken binds and validates parameter VRSToken from header.
func (o *VSphereListConnectionsParams) bindVRSToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("VRS-Token", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("VRS-Token", "header", raw); err != nil {
		return err
	}
	o.VRSToken = raw

	return nil
}
