// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetAllClustersOKCode is the HTTP code returned for type VSphereGetAllClustersOK
const VSphereGetAllClustersOKCode int = 200

/*
VSphereGetAllClustersOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetAllClustersOK
*/
type VSphereGetAllClustersOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetAllClustersOK creates VSphereGetAllClustersOK with default headers values
func NewVSphereGetAllClustersOK() *VSphereGetAllClustersOK {

	return &VSphereGetAllClustersOK{}
}

// WithPayload adds the payload to the v sphere get all clusters o k response
func (o *VSphereGetAllClustersOK) WithPayload(payload *models.ObjectCollection) *VSphereGetAllClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all clusters o k response
func (o *VSphereGetAllClustersOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetAllClustersBadRequestCode is the HTTP code returned for type VSphereGetAllClustersBadRequest
const VSphereGetAllClustersBadRequestCode int = 400

/*
VSphereGetAllClustersBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetAllClustersBadRequest
*/
type VSphereGetAllClustersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetAllClustersBadRequest creates VSphereGetAllClustersBadRequest with default headers values
func NewVSphereGetAllClustersBadRequest() *VSphereGetAllClustersBadRequest {

	return &VSphereGetAllClustersBadRequest{}
}

// WithPayload adds the payload to the v sphere get all clusters bad request response
func (o *VSphereGetAllClustersBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetAllClustersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all clusters bad request response
func (o *VSphereGetAllClustersBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllClustersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
