// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VSphereGetAllClustersSummaryHandlerFunc turns a function with the right signature into a v sphere get all clusters summary handler
type VSphereGetAllClustersSummaryHandlerFunc func(VSphereGetAllClustersSummaryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VSphereGetAllClustersSummaryHandlerFunc) Handle(params VSphereGetAllClustersSummaryParams) middleware.Responder {
	return fn(params)
}

// VSphereGetAllClustersSummaryHandler interface for that can handle valid v sphere get all clusters summary params
type VSphereGetAllClustersSummaryHandler interface {
	Handle(VSphereGetAllClustersSummaryParams) middleware.Responder
}

// NewVSphereGetAllClustersSummary creates a new http.Handler for the v sphere get all clusters summary operation
func NewVSphereGetAllClustersSummary(ctx *middleware.Context, handler VSphereGetAllClustersSummaryHandler) *VSphereGetAllClustersSummary {
	return &VSphereGetAllClustersSummary{Context: ctx, Handler: handler}
}

/*
	VSphereGetAllClustersSummary swagger:route GET /vsphere/{vcenter}/cluster vSphereGetAllClustersSummary

Gets the hosts found at the endpoint.
*/
type VSphereGetAllClustersSummary struct {
	Context *middleware.Context
	Handler VSphereGetAllClustersSummaryHandler
}

func (o *VSphereGetAllClustersSummary) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVSphereGetAllClustersSummaryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
