// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VSphereGetVMByNameHandlerFunc turns a function with the right signature into a v sphere get VM by name handler
type VSphereGetVMByNameHandlerFunc func(VSphereGetVMByNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VSphereGetVMByNameHandlerFunc) Handle(params VSphereGetVMByNameParams) middleware.Responder {
	return fn(params)
}

// VSphereGetVMByNameHandler interface for that can handle valid v sphere get VM by name params
type VSphereGetVMByNameHandler interface {
	Handle(VSphereGetVMByNameParams) middleware.Responder
}

// NewVSphereGetVMByName creates a new http.Handler for the v sphere get VM by name operation
func NewVSphereGetVMByName(ctx *middleware.Context, handler VSphereGetVMByNameHandler) *VSphereGetVMByName {
	return &VSphereGetVMByName{Context: ctx, Handler: handler}
}

/*
	VSphereGetVMByName swagger:route GET /vsphere/{vcenter}/vm/name/{vmname} vSphereGetVmByName

Retrieve a VM from a vCenter Server/ESXi host.
*/
type VSphereGetVMByName struct {
	Context *middleware.Context
	Handler VSphereGetVMByNameHandler
}

func (o *VSphereGetVMByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVSphereGetVMByNameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
