// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VSphereGetAllDatastoresHandlerFunc turns a function with the right signature into a v sphere get all datastores handler
type VSphereGetAllDatastoresHandlerFunc func(VSphereGetAllDatastoresParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VSphereGetAllDatastoresHandlerFunc) Handle(params VSphereGetAllDatastoresParams) middleware.Responder {
	return fn(params)
}

// VSphereGetAllDatastoresHandler interface for that can handle valid v sphere get all datastores params
type VSphereGetAllDatastoresHandler interface {
	Handle(VSphereGetAllDatastoresParams) middleware.Responder
}

// NewVSphereGetAllDatastores creates a new http.Handler for the v sphere get all datastores operation
func NewVSphereGetAllDatastores(ctx *middleware.Context, handler VSphereGetAllDatastoresHandler) *VSphereGetAllDatastores {
	return &VSphereGetAllDatastores{Context: ctx, Handler: handler}
}

/*
	VSphereGetAllDatastores swagger:route GET /vsphere/{vcenter}/datastore vSphereGetAllDatastores

Get a list of datastores
*/
type VSphereGetAllDatastores struct {
	Context *middleware.Context
	Handler VSphereGetAllDatastoresHandler
}

func (o *VSphereGetAllDatastores) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVSphereGetAllDatastoresParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
