// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VSphereGetVMByMoRefHandlerFunc turns a function with the right signature into a v sphere get VM by mo ref handler
type VSphereGetVMByMoRefHandlerFunc func(VSphereGetVMByMoRefParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VSphereGetVMByMoRefHandlerFunc) Handle(params VSphereGetVMByMoRefParams) middleware.Responder {
	return fn(params)
}

// VSphereGetVMByMoRefHandler interface for that can handle valid v sphere get VM by mo ref params
type VSphereGetVMByMoRefHandler interface {
	Handle(VSphereGetVMByMoRefParams) middleware.Responder
}

// NewVSphereGetVMByMoRef creates a new http.Handler for the v sphere get VM by mo ref operation
func NewVSphereGetVMByMoRef(ctx *middleware.Context, handler VSphereGetVMByMoRefHandler) *VSphereGetVMByMoRef {
	return &VSphereGetVMByMoRef{Context: ctx, Handler: handler}
}

/*
	VSphereGetVMByMoRef swagger:route GET /vsphere/{vcenter}/vm/moref/{moref} vSphereGetVmByMoRef

Retrieve a VM from a vCenter Server/ESXi host by it's Managed Object Reference.
*/
type VSphereGetVMByMoRef struct {
	Context *middleware.Context
	Handler VSphereGetVMByMoRefHandler
}

func (o *VSphereGetVMByMoRef) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVSphereGetVMByMoRefParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
