// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetAllStoragePodsSummaryOKCode is the HTTP code returned for type VSphereGetAllStoragePodsSummaryOK
const VSphereGetAllStoragePodsSummaryOKCode int = 200

/*
VSphereGetAllStoragePodsSummaryOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetAllStoragePodsSummaryOK
*/
type VSphereGetAllStoragePodsSummaryOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetAllStoragePodsSummaryOK creates VSphereGetAllStoragePodsSummaryOK with default headers values
func NewVSphereGetAllStoragePodsSummaryOK() *VSphereGetAllStoragePodsSummaryOK {

	return &VSphereGetAllStoragePodsSummaryOK{}
}

// WithPayload adds the payload to the v sphere get all storage pods summary o k response
func (o *VSphereGetAllStoragePodsSummaryOK) WithPayload(payload *models.ObjectCollection) *VSphereGetAllStoragePodsSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all storage pods summary o k response
func (o *VSphereGetAllStoragePodsSummaryOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllStoragePodsSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetAllStoragePodsSummaryBadRequestCode is the HTTP code returned for type VSphereGetAllStoragePodsSummaryBadRequest
const VSphereGetAllStoragePodsSummaryBadRequestCode int = 400

/*
VSphereGetAllStoragePodsSummaryBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetAllStoragePodsSummaryBadRequest
*/
type VSphereGetAllStoragePodsSummaryBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetAllStoragePodsSummaryBadRequest creates VSphereGetAllStoragePodsSummaryBadRequest with default headers values
func NewVSphereGetAllStoragePodsSummaryBadRequest() *VSphereGetAllStoragePodsSummaryBadRequest {

	return &VSphereGetAllStoragePodsSummaryBadRequest{}
}

// WithPayload adds the payload to the v sphere get all storage pods summary bad request response
func (o *VSphereGetAllStoragePodsSummaryBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetAllStoragePodsSummaryBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all storage pods summary bad request response
func (o *VSphereGetAllStoragePodsSummaryBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllStoragePodsSummaryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
