// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetHostByNameOKCode is the HTTP code returned for type VSphereGetHostByNameOK
const VSphereGetHostByNameOKCode int = 200

/*
VSphereGetHostByNameOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetHostByNameOK
*/
type VSphereGetHostByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetHostByNameOK creates VSphereGetHostByNameOK with default headers values
func NewVSphereGetHostByNameOK() *VSphereGetHostByNameOK {

	return &VSphereGetHostByNameOK{}
}

// WithPayload adds the payload to the v sphere get host by name o k response
func (o *VSphereGetHostByNameOK) WithPayload(payload *models.ObjectCollection) *VSphereGetHostByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get host by name o k response
func (o *VSphereGetHostByNameOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetHostByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetHostByNameBadRequestCode is the HTTP code returned for type VSphereGetHostByNameBadRequest
const VSphereGetHostByNameBadRequestCode int = 400

/*
VSphereGetHostByNameBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetHostByNameBadRequest
*/
type VSphereGetHostByNameBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetHostByNameBadRequest creates VSphereGetHostByNameBadRequest with default headers values
func NewVSphereGetHostByNameBadRequest() *VSphereGetHostByNameBadRequest {

	return &VSphereGetHostByNameBadRequest{}
}

// WithPayload adds the payload to the v sphere get host by name bad request response
func (o *VSphereGetHostByNameBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetHostByNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get host by name bad request response
func (o *VSphereGetHostByNameBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetHostByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
