// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VSphereGetAllResourcePoolHandlerFunc turns a function with the right signature into a v sphere get all resource pool handler
type VSphereGetAllResourcePoolHandlerFunc func(VSphereGetAllResourcePoolParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VSphereGetAllResourcePoolHandlerFunc) Handle(params VSphereGetAllResourcePoolParams) middleware.Responder {
	return fn(params)
}

// VSphereGetAllResourcePoolHandler interface for that can handle valid v sphere get all resource pool params
type VSphereGetAllResourcePoolHandler interface {
	Handle(VSphereGetAllResourcePoolParams) middleware.Responder
}

// NewVSphereGetAllResourcePool creates a new http.Handler for the v sphere get all resource pool operation
func NewVSphereGetAllResourcePool(ctx *middleware.Context, handler VSphereGetAllResourcePoolHandler) *VSphereGetAllResourcePool {
	return &VSphereGetAllResourcePool{Context: ctx, Handler: handler}
}

/*
	VSphereGetAllResourcePool swagger:route GET /vsphere/{vcenter}/resourcepool vSphereGetAllResourcePool

Gets the hosts found at the endpoint.
*/
type VSphereGetAllResourcePool struct {
	Context *middleware.Context
	Handler VSphereGetAllResourcePoolHandler
}

func (o *VSphereGetAllResourcePool) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVSphereGetAllResourcePoolParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
