// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VSphereChangeVMPowerStateHandlerFunc turns a function with the right signature into a v sphere change VM power state handler
type VSphereChangeVMPowerStateHandlerFunc func(VSphereChangeVMPowerStateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VSphereChangeVMPowerStateHandlerFunc) Handle(params VSphereChangeVMPowerStateParams) middleware.Responder {
	return fn(params)
}

// VSphereChangeVMPowerStateHandler interface for that can handle valid v sphere change VM power state params
type VSphereChangeVMPowerStateHandler interface {
	Handle(VSphereChangeVMPowerStateParams) middleware.Responder
}

// NewVSphereChangeVMPowerState creates a new http.Handler for the v sphere change VM power state operation
func NewVSphereChangeVMPowerState(ctx *middleware.Context, handler VSphereChangeVMPowerStateHandler) *VSphereChangeVMPowerState {
	return &VSphereChangeVMPowerState{Context: ctx, Handler: handler}
}

/*
	VSphereChangeVMPowerState swagger:route POST /vsphere/{vcenter}/vm/{moref}/power vSphereChangeVmPowerState

Power actions on the VM.
*/
type VSphereChangeVMPowerState struct {
	Context *middleware.Context
	Handler VSphereChangeVMPowerStateHandler
}

func (o *VSphereChangeVMPowerState) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVSphereChangeVMPowerStateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
