// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetAllNetworksOKCode is the HTTP code returned for type VSphereGetAllNetworksOK
const VSphereGetAllNetworksOKCode int = 200

/*
VSphereGetAllNetworksOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetAllNetworksOK
*/
type VSphereGetAllNetworksOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetAllNetworksOK creates VSphereGetAllNetworksOK with default headers values
func NewVSphereGetAllNetworksOK() *VSphereGetAllNetworksOK {

	return &VSphereGetAllNetworksOK{}
}

// WithPayload adds the payload to the v sphere get all networks o k response
func (o *VSphereGetAllNetworksOK) WithPayload(payload *models.ObjectCollection) *VSphereGetAllNetworksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all networks o k response
func (o *VSphereGetAllNetworksOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllNetworksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetAllNetworksBadRequestCode is the HTTP code returned for type VSphereGetAllNetworksBadRequest
const VSphereGetAllNetworksBadRequestCode int = 400

/*
VSphereGetAllNetworksBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetAllNetworksBadRequest
*/
type VSphereGetAllNetworksBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetAllNetworksBadRequest creates VSphereGetAllNetworksBadRequest with default headers values
func NewVSphereGetAllNetworksBadRequest() *VSphereGetAllNetworksBadRequest {

	return &VSphereGetAllNetworksBadRequest{}
}

// WithPayload adds the payload to the v sphere get all networks bad request response
func (o *VSphereGetAllNetworksBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetAllNetworksBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all networks bad request response
func (o *VSphereGetAllNetworksBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllNetworksBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
