// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetAllResourcePoolOKCode is the HTTP code returned for type VSphereGetAllResourcePoolOK
const VSphereGetAllResourcePoolOKCode int = 200

/*
VSphereGetAllResourcePoolOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetAllResourcePoolOK
*/
type VSphereGetAllResourcePoolOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetAllResourcePoolOK creates VSphereGetAllResourcePoolOK with default headers values
func NewVSphereGetAllResourcePoolOK() *VSphereGetAllResourcePoolOK {

	return &VSphereGetAllResourcePoolOK{}
}

// WithPayload adds the payload to the v sphere get all resource pool o k response
func (o *VSphereGetAllResourcePoolOK) WithPayload(payload *models.ObjectCollection) *VSphereGetAllResourcePoolOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all resource pool o k response
func (o *VSphereGetAllResourcePoolOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllResourcePoolOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetAllResourcePoolBadRequestCode is the HTTP code returned for type VSphereGetAllResourcePoolBadRequest
const VSphereGetAllResourcePoolBadRequestCode int = 400

/*
VSphereGetAllResourcePoolBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetAllResourcePoolBadRequest
*/
type VSphereGetAllResourcePoolBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetAllResourcePoolBadRequest creates VSphereGetAllResourcePoolBadRequest with default headers values
func NewVSphereGetAllResourcePoolBadRequest() *VSphereGetAllResourcePoolBadRequest {

	return &VSphereGetAllResourcePoolBadRequest{}
}

// WithPayload adds the payload to the v sphere get all resource pool bad request response
func (o *VSphereGetAllResourcePoolBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetAllResourcePoolBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all resource pool bad request response
func (o *VSphereGetAllResourcePoolBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllResourcePoolBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
