// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetVMByNameOKCode is the HTTP code returned for type VSphereGetVMByNameOK
const VSphereGetVMByNameOKCode int = 200

/*
VSphereGetVMByNameOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetVmByNameOK
*/
type VSphereGetVMByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetVMByNameOK creates VSphereGetVMByNameOK with default headers values
func NewVSphereGetVMByNameOK() *VSphereGetVMByNameOK {

	return &VSphereGetVMByNameOK{}
}

// WithPayload adds the payload to the v sphere get Vm by name o k response
func (o *VSphereGetVMByNameOK) WithPayload(payload *models.ObjectCollection) *VSphereGetVMByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get Vm by name o k response
func (o *VSphereGetVMByNameOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetVMByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetVMByNameBadRequestCode is the HTTP code returned for type VSphereGetVMByNameBadRequest
const VSphereGetVMByNameBadRequestCode int = 400

/*
VSphereGetVMByNameBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetVmByNameBadRequest
*/
type VSphereGetVMByNameBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetVMByNameBadRequest creates VSphereGetVMByNameBadRequest with default headers values
func NewVSphereGetVMByNameBadRequest() *VSphereGetVMByNameBadRequest {

	return &VSphereGetVMByNameBadRequest{}
}

// WithPayload adds the payload to the v sphere get Vm by name bad request response
func (o *VSphereGetVMByNameBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetVMByNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get Vm by name bad request response
func (o *VSphereGetVMByNameBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetVMByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
