// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetAllVMSummaryOKCode is the HTTP code returned for type VSphereGetAllVMSummaryOK
const VSphereGetAllVMSummaryOKCode int = 200

/*
VSphereGetAllVMSummaryOK Success

swagger:response vSphereGetAllVmSummaryOK
*/
type VSphereGetAllVMSummaryOK struct {

	/*
	  In: Body
	*/
	Payload *VSphereGetAllVMSummaryOKBody `json:"body,omitempty"`
}

// NewVSphereGetAllVMSummaryOK creates VSphereGetAllVMSummaryOK with default headers values
func NewVSphereGetAllVMSummaryOK() *VSphereGetAllVMSummaryOK {

	return &VSphereGetAllVMSummaryOK{}
}

// WithPayload adds the payload to the v sphere get all Vm summary o k response
func (o *VSphereGetAllVMSummaryOK) WithPayload(payload *VSphereGetAllVMSummaryOKBody) *VSphereGetAllVMSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all Vm summary o k response
func (o *VSphereGetAllVMSummaryOK) SetPayload(payload *VSphereGetAllVMSummaryOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllVMSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetAllVMSummaryBadRequestCode is the HTTP code returned for type VSphereGetAllVMSummaryBadRequest
const VSphereGetAllVMSummaryBadRequestCode int = 400

/*
VSphereGetAllVMSummaryBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetAllVmSummaryBadRequest
*/
type VSphereGetAllVMSummaryBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetAllVMSummaryBadRequest creates VSphereGetAllVMSummaryBadRequest with default headers values
func NewVSphereGetAllVMSummaryBadRequest() *VSphereGetAllVMSummaryBadRequest {

	return &VSphereGetAllVMSummaryBadRequest{}
}

// WithPayload adds the payload to the v sphere get all Vm summary bad request response
func (o *VSphereGetAllVMSummaryBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetAllVMSummaryBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all Vm summary bad request response
func (o *VSphereGetAllVMSummaryBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllVMSummaryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
