// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetAllDatastoresOKCode is the HTTP code returned for type VSphereGetAllDatastoresOK
const VSphereGetAllDatastoresOKCode int = 200

/*
VSphereGetAllDatastoresOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetAllDatastoresOK
*/
type VSphereGetAllDatastoresOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetAllDatastoresOK creates VSphereGetAllDatastoresOK with default headers values
func NewVSphereGetAllDatastoresOK() *VSphereGetAllDatastoresOK {

	return &VSphereGetAllDatastoresOK{}
}

// WithPayload adds the payload to the v sphere get all datastores o k response
func (o *VSphereGetAllDatastoresOK) WithPayload(payload *models.ObjectCollection) *VSphereGetAllDatastoresOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all datastores o k response
func (o *VSphereGetAllDatastoresOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllDatastoresOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetAllDatastoresBadRequestCode is the HTTP code returned for type VSphereGetAllDatastoresBadRequest
const VSphereGetAllDatastoresBadRequestCode int = 400

/*
VSphereGetAllDatastoresBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetAllDatastoresBadRequest
*/
type VSphereGetAllDatastoresBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetAllDatastoresBadRequest creates VSphereGetAllDatastoresBadRequest with default headers values
func NewVSphereGetAllDatastoresBadRequest() *VSphereGetAllDatastoresBadRequest {

	return &VSphereGetAllDatastoresBadRequest{}
}

// WithPayload adds the payload to the v sphere get all datastores bad request response
func (o *VSphereGetAllDatastoresBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetAllDatastoresBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all datastores bad request response
func (o *VSphereGetAllDatastoresBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllDatastoresBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
