// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewVSphereAPI creates a new VSphere instance
func NewVSphereAPI(spec *loads.Document) *VSphereAPI {
	return &VSphereAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		SessionListHandler: SessionListHandlerFunc(func(params SessionListParams) middleware.Responder {
			return middleware.NotImplemented("operation SessionList has not yet been implemented")
		}),
		SessionRegisterHandler: SessionRegisterHandlerFunc(func(params SessionRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation SessionRegister has not yet been implemented")
		}),
		VSphereConnectHandler: VSphereConnectHandlerFunc(func(params VSphereConnectParams) middleware.Responder {
			return middleware.NotImplemented("operation VSphereConnect has not yet been implemented")
		}),
		VSphereGetAllHostsSummaryHandler: VSphereGetAllHostsSummaryHandlerFunc(func(params VSphereGetAllHostsSummaryParams) middleware.Responder {
			return middleware.NotImplemented("operation VSphereGetAllHostsSummary has not yet been implemented")
		}),
		VSphereGetAllVMSummaryHandler: VSphereGetAllVMSummaryHandlerFunc(func(params VSphereGetAllVMSummaryParams) middleware.Responder {
			return middleware.NotImplemented("operation VSphereGetAllVMSummary has not yet been implemented")
		}),
		VSphereGetVMByMoRefHandler: VSphereGetVMByMoRefHandlerFunc(func(params VSphereGetVMByMoRefParams) middleware.Responder {
			return middleware.NotImplemented("operation VSphereGetVMByMoRef has not yet been implemented")
		}),
		VSphereGetVMByNameHandler: VSphereGetVMByNameHandlerFunc(func(params VSphereGetVMByNameParams) middleware.Responder {
			return middleware.NotImplemented("operation VSphereGetVMByName has not yet been implemented")
		}),
		VSphereListConnectionsHandler: VSphereListConnectionsHandlerFunc(func(params VSphereListConnectionsParams) middleware.Responder {
			return middleware.NotImplemented("operation VSphereListConnections has not yet been implemented")
		}),
	}
}

/*VSphereAPI HTTP server in Go with Swagger endpoints definition */
type VSphereAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// SessionListHandler sets the operation handler for the session list operation
	SessionListHandler SessionListHandler
	// SessionRegisterHandler sets the operation handler for the session register operation
	SessionRegisterHandler SessionRegisterHandler
	// VSphereConnectHandler sets the operation handler for the v sphere connect operation
	VSphereConnectHandler VSphereConnectHandler
	// VSphereGetAllHostsSummaryHandler sets the operation handler for the v sphere get all hosts summary operation
	VSphereGetAllHostsSummaryHandler VSphereGetAllHostsSummaryHandler
	// VSphereGetAllVMSummaryHandler sets the operation handler for the v sphere get all VM summary operation
	VSphereGetAllVMSummaryHandler VSphereGetAllVMSummaryHandler
	// VSphereGetVMByMoRefHandler sets the operation handler for the v sphere get VM by mo ref operation
	VSphereGetVMByMoRefHandler VSphereGetVMByMoRefHandler
	// VSphereGetVMByNameHandler sets the operation handler for the v sphere get VM by name operation
	VSphereGetVMByNameHandler VSphereGetVMByNameHandler
	// VSphereListConnectionsHandler sets the operation handler for the v sphere list connections operation
	VSphereListConnectionsHandler VSphereListConnectionsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *VSphereAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *VSphereAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *VSphereAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *VSphereAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *VSphereAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *VSphereAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *VSphereAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *VSphereAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *VSphereAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the VSphereAPI
func (o *VSphereAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.SessionListHandler == nil {
		unregistered = append(unregistered, "SessionListHandler")
	}
	if o.SessionRegisterHandler == nil {
		unregistered = append(unregistered, "SessionRegisterHandler")
	}
	if o.VSphereConnectHandler == nil {
		unregistered = append(unregistered, "VSphereConnectHandler")
	}
	if o.VSphereGetAllHostsSummaryHandler == nil {
		unregistered = append(unregistered, "VSphereGetAllHostsSummaryHandler")
	}
	if o.VSphereGetAllVMSummaryHandler == nil {
		unregistered = append(unregistered, "VSphereGetAllVMSummaryHandler")
	}
	if o.VSphereGetVMByMoRefHandler == nil {
		unregistered = append(unregistered, "VSphereGetVMByMoRefHandler")
	}
	if o.VSphereGetVMByNameHandler == nil {
		unregistered = append(unregistered, "VSphereGetVMByNameHandler")
	}
	if o.VSphereListConnectionsHandler == nil {
		unregistered = append(unregistered, "VSphereListConnectionsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *VSphereAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *VSphereAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *VSphereAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *VSphereAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *VSphereAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *VSphereAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the v sphere API
func (o *VSphereAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *VSphereAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/session/list"] = NewSessionList(o.context, o.SessionListHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/session/register"] = NewSessionRegister(o.context, o.SessionRegisterHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/vsphere/connect"] = NewVSphereConnect(o.context, o.VSphereConnectHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/vsphere/{vcenter}/host"] = NewVSphereGetAllHostsSummary(o.context, o.VSphereGetAllHostsSummaryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/vsphere/{vcenter}/vm"] = NewVSphereGetAllVMSummary(o.context, o.VSphereGetAllVMSummaryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/vsphere/{vcenter}/vm/moref/{moref}"] = NewVSphereGetVMByMoRef(o.context, o.VSphereGetVMByMoRefHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/vsphere/{vcenter}/vm/name/{vmname}"] = NewVSphereGetVMByName(o.context, o.VSphereGetVMByNameHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/vsphere/list"] = NewVSphereListConnections(o.context, o.VSphereListConnectionsHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *VSphereAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *VSphereAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *VSphereAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *VSphereAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *VSphereAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
