// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nelons/vsphere-rest-server/pkg/swagger/server/models"
)

// VSphereGetAllStoragePodsOKCode is the HTTP code returned for type VSphereGetAllStoragePodsOK
const VSphereGetAllStoragePodsOKCode int = 200

/*
VSphereGetAllStoragePodsOK Successful request. Returns JSON containing a count and the collection of objects.

swagger:response vSphereGetAllStoragePodsOK
*/
type VSphereGetAllStoragePodsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectCollection `json:"body,omitempty"`
}

// NewVSphereGetAllStoragePodsOK creates VSphereGetAllStoragePodsOK with default headers values
func NewVSphereGetAllStoragePodsOK() *VSphereGetAllStoragePodsOK {

	return &VSphereGetAllStoragePodsOK{}
}

// WithPayload adds the payload to the v sphere get all storage pods o k response
func (o *VSphereGetAllStoragePodsOK) WithPayload(payload *models.ObjectCollection) *VSphereGetAllStoragePodsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all storage pods o k response
func (o *VSphereGetAllStoragePodsOK) SetPayload(payload *models.ObjectCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllStoragePodsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VSphereGetAllStoragePodsBadRequestCode is the HTTP code returned for type VSphereGetAllStoragePodsBadRequest
const VSphereGetAllStoragePodsBadRequestCode int = 400

/*
VSphereGetAllStoragePodsBadRequest A general failure occured, more details are contained within the message.

swagger:response vSphereGetAllStoragePodsBadRequest
*/
type VSphereGetAllStoragePodsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewVSphereGetAllStoragePodsBadRequest creates VSphereGetAllStoragePodsBadRequest with default headers values
func NewVSphereGetAllStoragePodsBadRequest() *VSphereGetAllStoragePodsBadRequest {

	return &VSphereGetAllStoragePodsBadRequest{}
}

// WithPayload adds the payload to the v sphere get all storage pods bad request response
func (o *VSphereGetAllStoragePodsBadRequest) WithPayload(payload *models.BadRequestError) *VSphereGetAllStoragePodsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v sphere get all storage pods bad request response
func (o *VSphereGetAllStoragePodsBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VSphereGetAllStoragePodsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
