// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ObjectCollection object collection
//
// swagger:model ObjectCollection
type ObjectCollection struct {

	// count
	Count int64 `json:"count,omitempty"`

	// results
	Results []interface{} `json:"results"`
}

// Validate validates this object collection
func (m *ObjectCollection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this object collection based on context it is used
func (m *ObjectCollection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ObjectCollection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ObjectCollection) UnmarshalBinary(b []byte) error {
	var res ObjectCollection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
